EURO CUP/EURO/Login/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from EURO import app, conn, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
from EURO.models import showmatches, showstadiums, showeuro, showgroups, showFranceMatches, showFranceStadiums, showFranceGroups, Matches, Stadium, Euro, Group, FranceMatches, FranceStadiums, FranceGroups


from flask import Flask 
import psycopg2
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
import subprocess 

app = Flask(__name__)
app.config['SECRET_KEY'] = 'fc089b9218301ad987914c53481bff04'
# set your own database
db = "dbname='bank' user='postgres' host='localhost' password = '1234'"
conn = psycopg2.connect(db)
cur = conn.cursor()

Login = Blueprint('Login', __name__)

posts = [{}]


@Login.route("/")  
@Login.route("/home")
def home():
    return render_template('home.html', posts=posts)


@Login.route("/about")
def about():
    data1=showeuro()
    return render_template('about.html', data1=data1)

@Login.route("/groups")
def groups():
    data2=showgroups()
    return render_template('groups.html', data2=data2)

@Login.route("/matches")
def matches():
    books=showmatches()
    #books=cur.execute("SELECT stadium_name, cities FROM stadiums")
    return render_template("matches.html", books=books) #title='matches')
    #showmatches()
    #showstadiums()
    #return render_template('matches.html', title='matches')


@Login.route("/stadium")
def stadiums():
    data=showstadiums()
    #books=cur.execute("SELECT stadium_name, cities FROM stadiums")
    return render_template("stadiums.html", data=data) #title='matches')
    #showmatches()
    #showstadiums()
    #return render_template('matches.html', title='matches')

@Login.route("/francemat")
def francemat():
    data3=showFranceMatches()
    #books=cur.execute("SELECT stadium_name, cities FROM stadiums")
    return render_template("Francemat.html", data3=data3) #title='matches')
    #showmatches()
    #showstadiums()
    #return render_template('matches.html', title='matches')

@Login.route("/francestad")
def francestad():
    data4=showFranceStadiums()
    #books=cur.execute("SELECT stadium_name, cities FROM stadiums")
    return render_template("Francestad.html", data4=data4) #title='matches')
    #showmatches()
    #showstadiums()
    #return render_template('matches.html', title='matches')

@Login.route("/francegroup")
def francegroup():
    data5=showFranceGroups()
    #books=cur.execute("SELECT stadium_name, cities FROM stadiums")
    return render_template("Francegroup.html", data5=data5) #title='matches')
    #showmatches()
    #showstadiums()
    #return render_template('matches.html', title='matches')

@Login.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('Login.empty'))
    is_employee = True if request.args.get('is_employee') == 'true' else False
    form = EmployeeLoginForm() if is_employee else CustomerLoginForm()
    if form.validate_on_submit():
        user = select_Employees(form.id.data) if is_employee else select_Customers(form.id.data)
        if user != None and bcrypt.check_password_hash(user[2], form.password.data):
            login_user(user, remember=form.remember.data)
            flash('Login successful.','success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('Login.empty'))
        else:
            flash('Login Unsuccessful. Please check identifier and password', 'danger')
    return render_template('login.html', title='Login', is_employee=is_employee, form=form)


@Login.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('Login.home'))

EURO CUP/EURO/templates/France.html
<!DOCTYPE html>
<html lang="en"> 
<head>
<title>Page Title</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Untitled</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="assets/css/style.css">
</head>
<style>
* {
  box-sizing: border-box;
}

/* Style the body */
body {
  font-family: Arial, Helvetica, sans-serif;
  margin: 0;
}

/* Header/logo Title */
.header {
  padding: 30px;
  text-align: center;
  background: #326ef1;
  color: white;
}

/* Increase the font size of the heading */
.header h1 {
  font-size: 40px;
}

/* Style the top navigation bar */
.navbar {
  overflow: hidden;
  background-color: #326ef1;
}

/* Style the navigation bar links */
.navbar a {
  float: left;
  display: block;
  color: white;
  text-align: center;
  padding: 14px 20px;
  text-decoration: none;
}

/* Right-aligned link */
.navbar a.right {
  float: right;
}

/* Change color on hover */
.navbar a:hover {
  background-color: #ddd;
  color: black;
}

/* Column container */
.row {  
  display: -ms-flexbox; /* IE10 */
  display: flex;
  -ms-flex-wrap: wrap; /* IE10 */
  flex-wrap: wrap;
}

/* Create two unequal columns that sits next to each other */
/* Sidebar/left column */
.side {
  -ms-flex: 30%; /* IE10 */
  flex: 30%;
  background-color: #f1f1f1;
  padding: 20px;
}

/* Main column */
.main {   
  -ms-flex: 70%; /* IE10 */
  flex: 70%;
  background-color: white;
  padding: 20px;
}

/* Fake image, just for this example */
.fakeimg {
  background-color: #aaa;
  width: 100%;
  padding: 20px;
}

/* Footer */
.footer-basic {
  padding:40px 0;
  background-color:#ffffff;
  color:#4b4c4d;
}

.footer-basic ul {
  padding:0;
  list-style:none;
  text-align:center;
  font-size:18px;
  line-height:1.6;
  margin-bottom:0;
}

.footer-basic li {
  padding:0 10px;
}

.footer-basic ul a {
  color:inherit;
  text-decoration:none;
  opacity:0.8;
}

.footer-basic ul a:hover {
  opacity:1;
}

.footer-basic .social {
  text-align:center;
  padding-bottom:25px;
}

.footer-basic .social > a {
  font-size:24px;
  width:40px;
  height:40px;
  line-height:40px;
  display:inline-block;
  text-align:center;
  border-radius:50%;
  border:1px solid #ccc;
  margin:0 8px;
  color:inherit;
  opacity:0.75;
}

.footer-basic .social > a:hover {
  opacity:0.9;
}

.footer-basic .copyright {
  margin-top:15px;
  text-align:center;
  font-size:13px;
  color:#aaa;
  margin-bottom:0;
}

/* Responsive layout - when the screen is less than 700px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 700px) {
  .row {   
    flex-direction: column;
  }
}

/* Responsive layout - when the screen is less than 400px wide, make the navigation links stack on top of each other instead of next to each other */
@media screen and (max-width: 400px) {
  .navbar a {
    float: none;
    width: 100%;
  }
}
</style>
</head>
<body>

<div class="header">
  <h1>France data</h1>
</div>

<div class="navbar">
    <a class="nav-item nav-link" href="{{ url_for('Login.home') }}">Home</a>
    <a class="nav-item nav-link" href="{{ url_for('Login.about') }}">About</a>
    <a class="nav-item nav-link" href="{{ url_for('Login.groups') }}">Groups</a>
    <a class="nav-item nav-link" href="{{ url_for('Login.matches') }}">Matches</a>
    <a class="nav-item nav-link" href="{{ url_for('Login.stadiums') }}">Stadium</a>
</div>
</html>
<table class="table">
  <thead>
    <tr>
      <th>Nr</th>
      <th>Dates</th>
      <th>Time</th>
      <th>Teams</th>
      <th>Results</th>
    </tr>
  </thead>
  {% for row in data3 %}
  <tr>
      <td>{{row[0]}}</td>
      <td>{{row[1]}}</td>
      <td>{{row[2]}}</td>
      <td>{{row[3]}}</td>
      <td>{{row[4]}}</td>
  </tr>
  {% endfor %}
</table>
<table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Teams</th>
      </tr>
    </thead>
    {% for row in data5 %}
    <tr>
        <td>{{row[0]}}</td>
        <td>{{row[1]}}</td>
    </tr>
    {% endfor %}
  </table>
  <table class="table">
    <thead>
      <tr>
        <th>Stadium name</th>
        <th>City</th>
      </tr>
    </thead>
    {% for row in data4 %}
    <tr>
        <td>{{row[0]}}</td>
        <td>{{row[1]}}</td>
    </tr>
    {% endfor %}
  </table>

<div class="footer-basic">
  <footer>
     <div class="social"><a href="https://www.instagram.com/euro2020/?hl=da"><i class="icon ion-social-instagram"></i></a><a href="https://www.snapchat.com/l/da-dk/"><i class="icon ion-social-snapchat"></i></a><a href="https://twitter.com/euro2020"><i class="icon ion-social-twitter"></i></a><a href="https://www.facebook.com/EURO2020/"><i class="icon ion-social-facebook"></i></a></div>
     <ul class="list-inline">
        <li class="list-inline-item"><a href="{{ url_for('Login.home') }}">Home</a></li>
        <li class="list-inline-item"><a href="{{ url_for('Login.about') }}">About</a></li>
     </ul>
     <p class="copyright">BAR&MIC © 2021</p>
  </footer>
</div>

EURO CUP/EURO/templates/groups.html
<!DOCTYPE html>
<html lang="en"> 
<head>
<title>Page Title</title> 
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Untitled</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="assets/css/style.css">
</head>
<style>
* {
  box-sizing: border-box;
}

/* Style the body */
body {
  font-family: Arial, Helvetica, sans-serif;
  margin: 0;
}

/* Header/logo Title */
.header {
  padding: 30px;
  text-align: center;
  background: #326ef1;
  color: white;
}

/* Increase the font size of the heading */
.header h1 {
  font-size: 40px;
}

/* Style the top navigation bar */
.navbar {
  overflow: hidden;
  background-color: #326ef1;
}

/* Style the navigation bar links */
.navbar a {
  float: left;
  display: block;
  color: white;
  text-align: center;
  padding: 14px 20px;
  text-decoration: none;
}

/* Right-aligned link */
.navbar a.right {
  float: right;
}

/* Change color on hover */
.navbar a:hover {
  background-color: #ddd;
  color: black;
}

/* Column container */
.row {  
  display: -ms-flexbox; /* IE10 */
  display: flex;
  -ms-flex-wrap: wrap; /* IE10 */
  flex-wrap: wrap;
}

/* Create two unequal columns that sits next to each other */
/* Sidebar/left column */
.side {
  -ms-flex: 30%; /* IE10 */
  flex: 30%;
  background-color: #f1f1f1;
  padding: 20px;
}

/* Main column */
.main {   
  -ms-flex: 70%; /* IE10 */
  flex: 70%;
  background-color: white;
  padding: 20px;
}

/* Fake image, just for this example */
.fakeimg {
  background-color: #aaa;
  width: 100%;
  padding: 20px;
}

/* Footer */
.footer-basic {
  padding:40px 0;
  background-color:#ffffff;
  color:#4b4c4d;
}

.footer-basic ul {
  padding:0;
  list-style:none;
  text-align:center;
  font-size:18px;
  line-height:1.6;
  margin-bottom:0;
}

.footer-basic li {
  padding:0 10px;
}

.footer-basic ul a {
  color:inherit;
  text-decoration:none;
  opacity:0.8;
}

.footer-basic ul a:hover {
  opacity:1;
}

.footer-basic .social {
  text-align:center;
  padding-bottom:25px;
}

.footer-basic .social > a {
  font-size:24px;
  width:40px;
  height:40px;
  line-height:40px;
  display:inline-block;
  text-align:center;
  border-radius:50%;
  border:1px solid #ccc;
  margin:0 8px;
  color:inherit;
  opacity:0.75;
}

.footer-basic .social > a:hover {
  opacity:0.9;
}

.footer-basic .copyright {
  margin-top:15px;
  text-align:center;
  font-size:13px;
  color:#aaa;
  margin-bottom:0;
}

/* Responsive layout - when the screen is less than 700px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 700px) {
  .row {   
    flex-direction: column;
  }
}

/* Responsive layout - when the screen is less than 400px wide, make the navigation links stack on top of each other instead of next to each other */
@media screen and (max-width: 400px) {
  .navbar a {
    float: none;
    width: 100%;
  }
}
</style>
</head>
<body>

<div class="header">
  <h1>Groups</h1>
</div>

<div class="navbar">
    <a class="nav-item nav-link" href="{{ url_for('Login.home') }}">Home</a>
    <a class="nav-item nav-link" href="{{ url_for('Login.about') }}">About</a>
    <a class="nav-item nav-link" href="{{ url_for('Login.groups') }}">Groups</a>
    <a class="nav-item nav-link" href="{{ url_for('Login.matches') }}">Matches</a>
    <a class="nav-item nav-link" href="{{ url_for('Login.stadiums') }}">Stadium</a>
</div>

<p>These are the groups for the initial group phase of the Euro Cup 2021. Listed underneath is a link to the previous groups from the Euro cup 2016. </p>
</html>
<h2>Groups in Euro Cup 2021</h2>
<table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Teams</th>
      </tr>
    </thead>
    {% for row in data2 %}
    <tr>
        <td>{{row[0]}}</td>
        <td>{{row[1]}}</td>
    </tr>
    {% endfor %}
  </table>
  <h2>Groups in Euro Cup 2016</h2>
  <a href="{{ url_for('Login.francegroup') }}">Groups</a></li>
   </a>

  <div class="footer-basic">
   <footer>
      <div class="social"><a href="https://www.instagram.com/euro2020/?hl=da"><i class="icon ion-social-instagram"></i></a><a href="https://www.snapchat.com/l/da-dk/"><i class="icon ion-social-snapchat"></i></a><a href="https://twitter.com/euro2020"><i class="icon ion-social-twitter"></i></a><a href="https://www.facebook.com/EURO2020/"><i class="icon ion-social-facebook"></i></a></div>
      <ul class="list-inline">
         <li class="list-inline-item"><a href="{{ url_for('Login.home') }}">Home</a></li>
         <li class="list-inline-item"><a href="{{ url_for('Login.about') }}">About</a></li>
      </ul>
      <p class="copyright">BAR&MIC © 2021</p>
   </footer>
</div>

EURO CUP/EURO/templates/matches.html
<!DOCTYPE html>
<html lang="en"> 
<head>
<title>Page Title</title> 
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Untitled</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="assets/css/style.css">
</head>
<style>
* {
  box-sizing: border-box;
}

/* Style the body */
body {
  font-family: Arial, Helvetica, sans-serif;
  margin: 0;
}

/* Header/logo Title */
.header {
  padding: 30px;
  text-align: center;
  background: #326ef1;
  color: white;
}

/* Increase the font size of the heading */
.header h1 {
  font-size: 40px;
}

/* Style the top navigation bar */
.navbar {
  overflow: hidden;
  background-color: #326ef1;
}

/* Style the navigation bar links */
.navbar a {
  float: left;
  display: block;
  color: white;
  text-align: center;
  padding: 14px 20px;
  text-decoration: none;
}

/* Right-aligned link */
.navbar a.right {
  float: right;
}

/* Change color on hover */
.navbar a:hover {
  background-color: #ddd;
  color: black;
}

/* Column container */
.row {  
  display: -ms-flexbox; /* IE10 */
  display: flex;
  -ms-flex-wrap: wrap; /* IE10 */
  flex-wrap: wrap;
}

/* Create two unequal columns that sits next to each other */
/* Sidebar/left column */
.side {
  -ms-flex: 30%; /* IE10 */
  flex: 30%;
  background-color: #f1f1f1;
  padding: 20px;
}

/* Main column */
.main {   
  -ms-flex: 70%; /* IE10 */
  flex: 70%;
  background-color: white;
  padding: 20px;
}

/* Fake image, just for this example */
.fakeimg {
  background-color: #aaa;
  width: 100%;
  padding: 20px;
}

/* Footer */
.footer-basic {
  padding:40px 0;
  background-color:#ffffff;
  color:#4b4c4d;
}

.footer-basic ul {
  padding:0;
  list-style:none;
  text-align:center;
  font-size:18px;
  line-height:1.6;
  margin-bottom:0;
}

.footer-basic li {
  padding:0 10px;
}

.footer-basic ul a {
  color:inherit;
  text-decoration:none;
  opacity:0.8;
}

.footer-basic ul a:hover {
  opacity:1;
}

.footer-basic .social {
  text-align:center;
  padding-bottom:25px;
}

.footer-basic .social > a {
  font-size:24px;
  width:40px;
  height:40px;
  line-height:40px;
  display:inline-block;
  text-align:center;
  border-radius:50%;
  border:1px solid #ccc;
  margin:0 8px;
  color:inherit;
  opacity:0.75;
}

.footer-basic .social > a:hover {
  opacity:0.9;
}

.footer-basic .copyright {
  margin-top:15px;
  text-align:center;
  font-size:13px;
  color:#aaa;
  margin-bottom:0;
}
/* Responsive layout - when the screen is less than 700px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 700px) {
  .row {   
    flex-direction: column;
  }
}

/* Responsive layout - when the screen is less than 400px wide, make the navigation links stack on top of each other instead of next to each other */
@media screen and (max-width: 400px) {
  .navbar a {
    float: none;
    width: 100%;
  }
}
</style>
</head>
<body>

<div class="header">
  <h1>Matches</h1>
</div>

<div class="navbar">
    <a class="nav-item nav-link" href="{{ url_for('Login.home') }}">Home</a>
    <a class="nav-item nav-link" href="{{ url_for('Login.about') }}">About</a>
    <a class="nav-item nav-link" href="{{ url_for('Login.groups') }}">Groups</a>
    <a class="nav-item nav-link" href="{{ url_for('Login.matches') }}">Matches</a>
    <a class="nav-item nav-link" href="{{ url_for('Login.stadiums') }}">Stadium</a>
</div>
<p>These are the matches for the initial group phase of the Euro Cup 2021. Listed underneath is a link to the previous matches from the Euro cup 2016 including the knockout matches. </p>
<h2>Matches in Euro Cup 2021</h2>
<table class="table">
    <thead>
      <tr>
        <th>Nr</th>
        <th>Teams</th>
        <th>Time</th>
        <th>Date</th>
      </tr>
    </thead>
    {% for row in books %}
    <tr>
        <td>{{row[0]}}</td>
        <td>{{row[1]}}</td>
        <td>{{row[2]}}</td>
        <td>{{row[3]}}</td>
    </tr>
    {% endfor %}
  </table>
  <h2>Matches in Euro Cup 2016</h2>
  <a href="{{ url_for('Login.francemat') }}">Matches</a></li>
  </a>
  

  <div class="footer-basic">
    <footer>
       <div class="social"><a href="https://www.instagram.com/euro2020/?hl=da"><i class="icon ion-social-instagram"></i></a><a href="https://www.snapchat.com/l/da-dk/"><i class="icon ion-social-snapchat"></i></a><a href="https://twitter.com/euro2020"><i class="icon ion-social-twitter"></i></a><a href="https://www.facebook.com/EURO2020/"><i class="icon ion-social-facebook"></i></a></div>
       <ul class="list-inline">
          <li class="list-inline-item"><a href="{{ url_for('Login.home') }}">Home</a></li>
          <li class="list-inline-item"><a href="{{ url_for('Login.about') }}">About</a></li>
       </ul>
       <p class="copyright">BAR&MIC © 2021</p>
    </footer>
</div>
 

EURO CUP/EURO/templates/stadiums.html
<!DOCTYPE html>
<html lang="en"> 
<head>
<title>Page Title</title> 
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Untitled</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="assets/css/style.css">
</head>
<style>
* {
  box-sizing: border-box;
}

/* Style the body */
body {
  font-family: Arial, Helvetica, sans-serif;
  margin: 0;
}

/* Header/logo Title */
.header {
  padding: 30px;
  text-align: center;
  background: #326ef1;
  color: white;
}

/* Increase the font size of the heading */
.header h1 {
  font-size: 40px;
}

/* Style the top navigation bar */
.navbar {
  overflow: hidden;
  background-color: #326ef1;
}

/* Style the navigation bar links */
.navbar a {
  float: left;
  display: block;
  color: white;
  text-align: center;
  padding: 14px 20px;
  text-decoration: none;
}

/* Right-aligned link */
.navbar a.right {
  float: right;
}

/* Change color on hover */
.navbar a:hover {
  background-color: #ddd;
  color: black;
}

/* Column container */
.row {  
  display: -ms-flexbox; /* IE10 */
  display: flex;
  -ms-flex-wrap: wrap; /* IE10 */
  flex-wrap: wrap;
}

/* Create two unequal columns that sits next to each other */
/* Sidebar/left column */
.side {
  -ms-flex: 30%; /* IE10 */
  flex: 30%;
  background-color: #f1f1f1;
  padding: 20px;
}

/* Main column */
.main {   
  -ms-flex: 70%; /* IE10 */
  flex: 70%;
  background-color: white;
  padding: 20px;
}

/* Fake image, just for this example */
.fakeimg {
  background-color: #aaa;
  width: 100%;
  padding: 20px;
}

/* Footer */
.footer-basic {
  padding:40px 0;
  background-color:#ffffff;
  color:#4b4c4d;
}

.footer-basic ul {
  padding:0;
  list-style:none;
  text-align:center;
  font-size:18px;
  line-height:1.6;
  margin-bottom:0;
}

.footer-basic li {
  padding:0 10px;
}

.footer-basic ul a {
  color:inherit;
  text-decoration:none;
  opacity:0.8;
}

.footer-basic ul a:hover {
  opacity:1;
}

.footer-basic .social {
  text-align:center;
  padding-bottom:25px;
}

.footer-basic .social > a {
  font-size:24px;
  width:40px;
  height:40px;
  line-height:40px;
  display:inline-block;
  text-align:center;
  border-radius:50%;
  border:1px solid #ccc;
  margin:0 8px;
  color:inherit;
  opacity:0.75;
}

.footer-basic .social > a:hover {
  opacity:0.9;
}

.footer-basic .copyright {
  margin-top:15px;
  text-align:center;
  font-size:13px;
  color:#aaa;
  margin-bottom:0;
}

/* Responsive layout - when the screen is less than 700px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 700px) {
  .row {   
    flex-direction: column;
  }
}

/* Responsive layout - when the screen is less than 400px wide, make the navigation links stack on top of each other instead of next to each other */
@media screen and (max-width: 400px) {
  .navbar a {
    float: none;
    width: 100%;
  }
}
</style>
</head>
<body>

<div class="header">
  <h1>Stadiums</h1>
</div>

<div class="navbar">
    <a class="nav-item nav-link" href="{{ url_for('Login.home') }}">Home</a>
    <a class="nav-item nav-link" href="{{ url_for('Login.about') }}">About</a>
    <a class="nav-item nav-link" href="{{ url_for('Login.groups') }}">Groups</a>
    <a class="nav-item nav-link" href="{{ url_for('Login.matches') }}">Matches</a>
    <a class="nav-item nav-link" href="{{ url_for('Login.stadiums') }}">Stadium</a>
</div>
<p>Ready to kick off your UEFA EURO 2020 adventure in the cities?</p>
<p>Whether you’re a ticket holder or just want to be part of the football madness, here is a list of the stadiums!</p>
<h2>Stadiums in Euro Cup 2021</h2>
<table class="table">
    <thead>
      <tr>
        <th>Stadium</th>
        <th>City</th>
      </tr>
    </thead>
    {% for row in data %}
    <tr>
        <td>{{row[0]}}</td>
        <td>{{row[1]}}</td>
    </tr>
    {% endfor %}
  </table>
  <h2>Stadiums in Euro Cup 2016</h2>
  <a href="{{ url_for('Login.francestad') }}">Stadiums</a></li>
  </a>

  <div class="footer-basic">
    <footer>
       <div class="social"><a href="https://www.instagram.com/euro2020/?hl=da"><i class="icon ion-social-instagram"></i></a><a href="https://www.snapchat.com/l/da-dk/"><i class="icon ion-social-snapchat"></i></a><a href="https://twitter.com/euro2020"><i class="icon ion-social-twitter"></i></a><a href="https://www.facebook.com/EURO2020/"><i class="icon ion-social-facebook"></i></a></div>
       <ul class="list-inline">
          <li class="list-inline-item"><a href="{{ url_for('Login.home') }}">Home</a></li>
          <li class="list-inline-item"><a href="{{ url_for('Login.about') }}">About</a></li>
       </ul>
       <p class="copyright">BAR&MIC © 2021</p>
    </footer>
</div>
